# Generated by Django 5.1.1 on 2024-10-11 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactdetails',
            new_name='fit',
        ),
    ]
